name: Release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  prepare-release:
    runs-on: ubuntu-24.04
    outputs:
      version-id: ${{ steps.get_vars.outputs.VERSION_ID }}
      tag-name: ${{ steps.get_vars.outputs.TAG_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci
      - name: Setup variables
        id: get_vars
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          echo "VERSION_ID=${TAG#v}" >> $GITHUB_ENV
          echo "VERSION_ID=${TAG#v}" >> $GITHUB_OUTPUT
          echo "TAG_NAME=$TAG" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG" >> $GITHUB_OUTPUT
      - name: Fetch release body
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          releaseName: ${{ env.TAG_NAME }}
          draft: true
          doNotFailIfNotFound: true
      - name: Write release body
        env:
          RELEASE_BODY: ${{ steps.release.outputs.body }}
        run: |
          echo "$RELEASE_BODY" >> RELEASE.md
          echo "## Changelog" >> RELEASE.md
          npx changelog get -v $VERSION_ID >> RELEASE.md
      - name: Update release
        uses: Wandalen/wretry.action@v3
        with:
          action: ncipollo/release-action@v1
          attempt_limit: 5
          attempt_delay: 250
          with: |
            allowUpdates: true
            name: ${{ env.TAG_NAME }}
            draft: true
            tag: ${{ env.VERSION_ID }}
            bodyFile: RELEASE.md

  release:
    permissions:
      contents: write
      id-token: write
    needs: prepare-release
    runs-on: ubuntu-24.04
    env:
      VERSION_ID: ${{ needs.prepare-release.outputs.version-id }}
      TAG_NAME: ${{ needs.prepare-release.outputs.tag-name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci
      - name: Publish wrapper
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public
      - name: Update release
        uses: Wandalen/wretry.action@v3
        with:
          action: ncipollo/release-action@v1
          attempt_limit: 5
          attempt_delay: 250
          with: |
            allowUpdates: true
            name: ${{ env.TAG_NAME }}
            draft: false
            omitBodyDuringUpdate: true
            replacesArtifacts: false
            tag: ${{ env.VERSION_ID }}
